[build]
  command = "npx prisma generate && npx prisma db push && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  DATABASE_URL = "postgresql://neondb_owner:npg_ut6LlJNPOX0a@ep-summer-cloud-axb95yiz-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
